name: Reusable - Microservices

on:
  workflow_call:
    inputs:
      microservice-id:
        required: true
        type: string

permissions:
  id-token: none
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build application
        run: mvn clean compile

      - name: Run tests
        run: mvn test --batch-mode --fail-at-end

      - name: Package application
        run: mvn package

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.microservice-id }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.microservice-id }}:${{ github.sha }}

  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.3'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::289389227463:role/github-org-soat1-grupo18
          aws-region: us-east-1

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name fiap-cluster

      - uses: Azure/k8s-deploy@v4
        with:
          namespace: 'myapp'
          manifests: |
              kubernetes/
          images: '${{ secrets.DOCKER_HUB_USER }}/${{ inputs.microservice-id }}:${{ github.sha }}'
