name: Reusable - Microservices

on:
  workflow_call:
    inputs:
      microservice-id:
        required: true
        type: string

permissions:
  id-token: none
  contents: read

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build application
        run: mvn clean compile

      - name: Run tests
        run: mvn test --batch-mode --fail-at-end

      - name: Package application
        run: mvn package

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.microservice-id }}:${{ github.sha }} .

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.microservice-id }}:${{ github.sha }}

  build-and-deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}